import dotenv from "dotenv";
dotenv.config();

export const MONGO_URI = process.env.MONGO_URI;
export const MONGO_DB_NAME = process.env.MONGO_DB_NAME;

export const ROLES = {
  ADMIN: "ADMIN",
  LENDER: "LENDER",
  DEALER: "DEALER",
};

export const CUSTOMER_KYC_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
};

export const LOAN_APPLICATION_STATUS = {
  APPLIED: "APPLIED",
  KYC_PENDING: "KYC_PENDING",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  DISBURSED: "DISBURSED",
  CLOSED: "CLOSED",
  DEFAULTED: "DEFAULTED",
};

export const LOAN_CONTRACT_STATUS = {
  APPROVED: "APPROVED",
  DISBURSED: "DISBURSED",
  ACTIVE: "ACTIVE",
  DELINQUENT: "DELINQUENT",
  NPA: "NPA",
  CLOSED: "CLOSED",
};

export const EMI_STATUS = {
  PENDING: "PENDING",
  PAID: "PAID",
  PARTIAL: "PARTIAL",
  OVERDUE: "OVERDUE",
};

export const COLLECTION_STATUS = {
  COLLECTED: "COLLECTED",
  PENDING_LENDER_CONFIRMATION: "PENDING_LENDER_CONFIRMATION",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const PAYMENT_MODES = {
  RAZORPAY: "RAZORPAY",
  UPI: "UPI",
  CASH: "CASH",
  BANK: "BANK",
};

export const CHANNELS = {
  SMS: "SMS",
  EMAIL: "EMAIL",
  WHATSAPP: "WHATSAPP",
  PUSH: "PUSH",
};

export const LEDGER_ACCOUNT_TYPES = {
  CUSTOMER_LOAN_ACCOUNT: "CUSTOMER_LOAN_ACCOUNT",
  LENDER_SETTLEMENT_ACCOUNT: "LENDER_SETTLEMENT_ACCOUNT",
  DEALER_COMMISSION_ACCOUNT: "DEALER_COMMISSION_ACCOUNT",
  INTEREST_INCOME_ACCOUNT: "INTEREST_INCOME_ACCOUNT",
  PRINCIPAL_RECEIVABLE_ACCOUNT: "PRINCIPAL_RECEIVABLE_ACCOUNT",
  CASH_COLLECTION_ACCOUNT: "CASH_COLLECTION_ACCOUNT",
  PAYMENT_GATEWAY_ACCOUNT: "PAYMENT_GATEWAY_ACCOUNT",
};

export const LEDGER_TRANSACTION_TYPES = {
  DEBIT: "DEBIT",
  CREDIT: "CREDIT",
};
